### ISSUE TITLE
error: no matching function for call to ...

### ISSUE THREAD

**Issue by bryceadams** [sparkfun/SparkFun_MAX17043_Particle_Library#1]
When flashing a photon:

![screen](https://cldup.com/JM_LV_H-eg.png)

**Comment by jimblom** [comment]
Fixed with the [latest commit](https://github.com/sparkfun/SparkFun_MAX17043_Particle_Library/commit/b0f54a75f6e8af10ef6b082f75bca259fb737f2a). Thanks for the heads up!
