### ISSUE TITLE
Clear Alert Bit

### ISSUE THREAD

**Issue by simontom** [sparkfun/SparkFun_MAX17043_Particle_Library#6]
https://github.com/sparkfun/SparkFun_MAX17043_Particle_Library/blob/master/firmware/SparkFunMAX17043.cpp#L139

https://github.com/sparkfun/SparkFun_MAX17043_Particle_Library/blob/master/firmware/SparkFunMAX17043.cpp#L148

https://github.com/sparkfun/SparkFun_MAX17043_Particle_Library/blob/master/firmware/SparkFunMAX17043.cpp#L152

I think there should be "(1 << 5)"

**Comment by simontom** [comment]
It is defined in .h file

https://github.com/sparkfun/SparkFun_MAX17043_Particle_Library/blob/master/firmware/SparkFunMAX17043.cpp#L38

**Comment by jimblom** [comment]
Good catch! Fixed in the latest commit, release 1.1.3.

**Comment by simontom** [comment]
Yaaaay, happy I could help. :angel:
